// order-placement-service/src/saga.constants.ts
export enum SagaState {
  ORDER_INITIATED = 'ORDER_INITIATED',
  ORDER_SAVED = 'ORDER_SAVED',
  BYBIT_ORDER_PLACED = 'BYBIT_ORDER_PLACED',
  TELEGRAM_NOTIFIED = 'TELEGRAM_NOTIFIED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum SagaEvent {
  INITIATE_ORDER = 'INITIATE_ORDER',
  SAVE_ORDER = 'SAVE_ORDER',
  PLACE_BYBIT_ORDER = 'PLACE_BYBIT_ORDER',
  SEND_TELEGRAM_MESSAGE = 'SEND_TELEGRAM_MESSAGE',
  COMPENSATE_ORDER = 'COMPENSATE_ORDER',
}
